# Docker

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image

  jobs:
  - job: Build
    displayName: Build
    pool:
      f4yiee
      # vmImage: ubuntu-latest
    steps:
    
    - task: Docker@2
      inputs:
        containerRegistry: 'docker-hub'
        repository: 'swiggy-app'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'whoami'
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
